server:
  port: 8080
  servlet:
    context-path: /report

spring:
  application:
    name: edu-service
  profiles:
    active: local
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always