server:
  port: 8080

spring:
  application:
    name: report-service

  datasource:
    url: ${REPORT_DATASOURCE_URL}
    username: ${REPORT_DATASOURCE_USERNAME}
    password: ${REPORT_DATASOURCE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always