spring:
  config:
    activate:
      on-profile: k8s

  datasource:
    url: ${REPORT_DATASOURCE_URL}
    username: ${REPORT_DATASOURCE_USERNAME}
    password: ${REPORT_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true